import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "../styles/Home.module.scss";
import Todo from "@/components/Todo/Index";
import { useContext, useEffect } from "react";
import { MainContext } from "@/store";
import EmptyTodo from "@/components/EmptyTodo";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { state, dispatch } = useContext(MainContext);

  useEffect(() => {
    let items = JSON.parse(localStorage.getItem("todoText"));
    items &&
      dispatch({
        type: "GET-STORAGE",
        payload: items,
      });
  }, []);



  return (
    <>
      <Head>
        <title>Turtle to-do</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/dubTurtle.png" />
      </Head>

      {state.length > 0 ? <Todo /> : <EmptyTodo />}
    </>
  );
}
